# Generated by Django 3.0.7 on 2020-06-14 19:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
