# Generated by Django 3.0.8 on 2020-08-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200614_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='quote',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
