# Generated by Django 3.0.8 on 2020-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default='Zorro', max_length=100),
            preserve_default=False,
        ),
    ]
