# Generated by Django 3.0.8 on 2020-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200815_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='quote',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
